fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  lane :test do 
    UI.message "Testing complete"
  end

  lane :lint do 
    UI.message "lint complete"
  end

  lane :trigger_release do 
    UI.message "trigger_release complete"
    increment_build_number
    UI.message "Incrementing to build #{lane_context[SharedValues::BUILD_NUMBER]}"
    
    commit_version_bump(message: "Bump build to #{lane_context[SharedValues::BUILD_NUMBER]}",
                        xcodeproj: "ActionTesting.xcodeproj")

#     push_to_git_remote
    sh('git push https://${ENV["PAT"]}@github.com/<GITHUB_USERNAME>/<REPOSITORY_NAME>.git')
  end

  lane :release do 
    UI.message "release complete"
  end
end
