fastlane_version "2.27.0"
default_platform :ios

platform :ios do
  lane :test do 
    UI.message "Testing complete"
  end

  lane :lint do 
    UI.message "lint complete"
  end

  lane :trigger_release do 
    UI.message "trigger_release complete"
    increment_build_number
    UI.message "Incrementing to build #{lane_context[SharedValues::BUILD_NUMBER]}"
    
    commit_version_bump(message: "Bump build to #{lane_context[SharedValues::BUILD_NUMBER]}",
                        xcodeproj: "ActionTesting.xcodeproj")

#     push_to_git_remote
    sh("echo PAT - $PAT - $ENV['PAT'] - ${ENV['PAT']}")
    sh("echo REPO - `git remote -v`")
    sh("git push https://$PAT@github.com/Richard-Gist/actions-testing.git")
  end

  lane :release do 
    UI.message "release complete"
  end
end
