# This is a basic workflow to help you get started with Actions

name: After pull request

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_run:
    workflows: [ "Verify Pull Request", "Run super secret sonarcloud stuff" ]
#     branches: [ main ]
    types: [ completed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo Success!
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo Failure!!!!!!!
  # This workflow contains a single job called "build"
  on-forked:
    runs-on: ubuntu-latest
    if: ${{ github.event.push.repository.fork == true }}
    steps:
      - run: echo This was a fork
  not-forked:
    runs-on: ubuntu-latest
    if: ${{ github.event.push.repository.fork == false }}
    steps:
      - run: echo Is this a spoon?
  from-tyler:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'Richard-Gist/actions-testing' }}
    steps:
      - run: echo this is running on the original repository
