name: MEGA_CI

on: [ push, workflow_dispatch, pull_request ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  #     - name: Run TESTS
  #       run: fastlane unit_test
  #     - name: Generate SonarCloud Friendly Coverage Report
  #       run: ./xccov-to-sonarqube-generic.sh ~/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult > sq-generic.xml
  #     - name: Upload Coverage Report
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: sq-generic.xml
  #         path: sq-generic.xml
  #         retention-days: 1

  sonar_scan:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  #     - name: Download Coverage Report
  #       uses: actions/download-artifact@v2
  #       with:
  #         name: sq-generic.xml
  #         path: artifacts
  #     - name: Rename Paths in Coverage
  #       run:  sed 's+/Users/runner/work/Workflow/Workflow/++g' artifacts/sq-generic.xml > sq-generic.xml
  #     - name: SonarCloud Scan
  #       uses: sonarsource/sonarcloud-github-action@master
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build_for_package_managers:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
  #     - name: Validate SwiftPM BUILDs
  #       run: fastlane build_swiftpm
  #     - name: Validate Cocoapods Can Deploy (lib lint)
  #       run: fastlane cocoapods_liblint

  version_bump:
    runs-on: macos-latest
    if: ${{ github.event.pull_request.merged == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Bump version in Podspec and Plist
        id: bump_version
        run: |
          fastlane minor
          VERSION=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" ActionTesting/Info.plist`
          echo "##[set-output name=version;]$VERSION"
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[ci skip] Apply automatic changes"
          tagging_message: "${{ steps.bump_version.outputs.version }}"
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: ".github/configuration_complex.json"
          owner: "Richard-Gist"
          ignorePreReleases: "false"
          toTag: ${{ steps.bump_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug changelog
        run: echo "${{steps.build_changelog.outputs.changelog}}"

      - name: Create a GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.version }}
          release_name: Release ${{ steps.bump_version.outputs.version }}
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
