name: Merged_Pull_Request

on:
  workflow_dispatch:
    inputs:
      override:
        description: 'Run for manual dispatch'
        type: boolean
        required: true
        default: true
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: fastlane test
          
  lint:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run SwiftLint
        run: fastlane lint
        
  test2:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: fastlane test

  begin_release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}
      
      - name: version bump
        run: fastlane trigger_release
        env:
          PAT: ${{ secrets.PAT }}
