# This workflow should run for PRs
# It should be safe and secure to do so.

name: Verify Pull Request
on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo Verified!
