# This is a basic workflow that is manually triggered

name: Run super secret sonarcloud stuff

# Controlasdfdsas when thfdsasdfsasdfe action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  job_with_secret:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: This one does not expose secrets
      run: |
        echo "Hello1 ${{ secrets.PAT }}"
        echo "Hello2 ${{ secrets.PAT }}"
        echo "Hello3 ${{ secrets.PAT }}"
  
#   careless_job_with_secret:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#     # Runs a single command using the runners shell
#     - name: This one exposes secrets
#       run: | 
#         echo "${{ secrets.PAT }}"
#         echo "${{ secrets.PAT }}" | base64
#         echo "${{ secrets.PAT }}" | base64 | base64 --decode
