name: Version Bump

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types: [ completed ]

jobs:
  version_bump:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version in Podspec and Plist
        id: bump_version
        run: |
          fastlane minor
          VERSION=`/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" Sources/CucumberSwift/Info.plist`
          echo "##[set-output name=version;]$VERSION"
      - name: Commit version changes
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
          custom_tag: ${{ steps.bump_version.outputs.version }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
            fromTag: "1.0.0"
            toTag: "${{ steps.bump_version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug changelog
        run: echo "${{steps.github_release.outputs.changelog}}"

      - name: "Complex Configuration"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v1.7.3
        with:
          configuration: "configuration_complex.json"
          owner: "Richard-Gist"
          ignorePreReleases: "false"
          fromTag: "1.0.0"
          toTag: ${{ steps.bump_version.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Debug changelog
        run: echo "${{steps.build_changelog.outputs.changelog}}"

      - name: Create a GitHub release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.build_changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        